### ISSUE TITLE
Clarification about OFFERED CONTRACTS

### ISSUE THREAD

**Issue by mgalyean** [JonnyOThan/kOS-Career#4]
In the Alt-F12 menu under contracts, one can see offered contracts also, are these also generated at time of query as described in the ADDON docs?

:OFFEREDCONTRACTS()

Returns a list of offered CONTRACTs. Note that this function has side effects: KSP does not generate contracts until you open the mission control window. Similarly, calling this function will regenerate the list of offered contracts.

I post this here in case the offered contracts actually do pre-exist going to the Mission Control scene and maybe there is a way to get to them without being regenerated?  Shot in the dark, no big deal

**Comment by JonnyOThan** [comment]
I'm pretty sure the debug menu does *not* refresh the list of contracts.  Yes it's certainly possible to not refresh them, but my intention with kos-career is to stay as close as possible to the stock career experience (just make it possible to automate it).
